# Generated by Django 3.2.15 on 2022-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('scode', models.IntegerField()),
                ('join', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('apid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=30)),
                ('dphone', models.IntegerField()),
                ('demail', models.CharField(max_length=50)),
                ('dspec', models.CharField(max_length=20)),
                ('daddress', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=20)),
                ('exper', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('join', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hdate', models.DateField()),
                ('htime', models.TimeField()),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=30)),
                ('dphone', models.IntegerField()),
                ('demail', models.CharField(max_length=50)),
                ('dspec', models.CharField(max_length=20)),
                ('daddress', models.CharField(max_length=100)),
                ('sym1', models.CharField(max_length=30)),
                ('sym2', models.CharField(max_length=30)),
                ('sym3', models.CharField(max_length=30)),
                ('sym4', models.CharField(max_length=30)),
                ('sym5', models.CharField(max_length=30)),
                ('disease', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('bgroup', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('join', models.DateTimeField()),
            ],
        ),
    ]
